/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package tomocomd.camps.mdlais.gui.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author jricardo
 */
public class OverviewDialog extends javax.swing.JDialog 
{
    /**
     * Creates new form OverviewDialog
     */
    public OverviewDialog(java.awt.Frame parent, boolean modal) throws IOException 
    {
        super(parent, modal);
        
        initComponents();
        
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screen.width/2 - getSize().width/2, screen.height/2 - getSize().height/2);
        setIconImage(new ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/appico.png")).getImage());
        
        jTextPane1.setPage(getClass().getResource( "/tomocomd/camps/mdlais/gui/data/webpages/overview/what_MDLAIS.html" ));
        jTextPane3.setPage(getClass().getResource( "/tomocomd/camps/mdlais/gui/data/webpages/overview/concepts.html" ));
        jTextPane2.setPage(getClass().getResource( "/tomocomd/camps/mdlais/gui/data/webpages/overview/kit.html" ));
        
        jTabbedPane1.removeTabAt( 2 );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Overview");
        setIconImage(new ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/appico.png")).getImage());
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(550, 390));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(550, 390));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(550, 390));

        jTextPane1.setMaximumSize(new java.awt.Dimension(550, 390));
        jTextPane1.setMinimumSize(new java.awt.Dimension(550, 390));
        jTextPane1.setPreferredSize(new java.awt.Dimension(550, 390));
        jScrollPane4.setViewportView(jTextPane1);

        jTabbedPane1.addTab("What is ToMoCoMD-CAMPS MD-LAIs?", jScrollPane4);

        jTextPane2.setMaximumSize(new java.awt.Dimension(550, 390));
        jTextPane2.setMinimumSize(new java.awt.Dimension(550, 390));
        jTextPane2.setPreferredSize(new java.awt.Dimension(550, 390));
        jScrollPane5.setViewportView(jTextPane2);

        jTabbedPane1.addTab("Chemistry Development Kit ", jScrollPane5);

        jTextPane3.setMaximumSize(new java.awt.Dimension(550, 390));
        jTextPane3.setMinimumSize(new java.awt.Dimension(550, 390));
        jTextPane3.setPreferredSize(new java.awt.Dimension(550, 390));
        jScrollPane6.setViewportView(jTextPane3);

        jTabbedPane1.addTab("Definitions and Concepts", jScrollPane6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
