/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package tomocomd.camps.mdlais.gui.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author yasilvalmeida
 */
public class TipsDialog extends javax.swing.JDialog 
{
    private int index = 0;
    private List<String> tips_list;
    
    public TipsDialog(java.awt.Frame parent, boolean modal) throws IOException 
    {
        super(parent, modal);
        
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/appico.png")).getImage());
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(screen.width/2 - getSize().width/2, screen.height/2 - getSize().height/2);
        
        tips_list = new ArrayList<>();
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips1.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips2.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips4.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips5.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips9.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips10.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips12.html");
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips14.html"); 
        tips_list.add("/tomocomd/camps/mdlais/gui/data/webpages/tips/tips18.html"); 
        
        text_panel.setPage(getClass().getResource(tips_list.get(index)));
        jLabel1.setText("Tip: " + (index + 1) + " of " + tips_list.size());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bt_prev = new javax.swing.JButton();
        bt_next = new javax.swing.JButton();
        bt_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_panel = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Tips");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(506, 360));
        setName("tipsDialog"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bt_prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/tipsnext.png"))); // NOI18N
        bt_prev.setText("Previous");
        bt_prev.setMaximumSize(new java.awt.Dimension(115, 27));
        bt_prev.setMinimumSize(new java.awt.Dimension(115, 27));
        bt_prev.setPreferredSize(new java.awt.Dimension(115, 27));
        bt_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prevActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 0);
        getContentPane().add(bt_prev, gridBagConstraints);

        bt_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/tipsback.png"))); // NOI18N
        bt_next.setText("Next");
        bt_next.setDefaultCapable(false);
        bt_next.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bt_next.setMaximumSize(new java.awt.Dimension(115, 27));
        bt_next.setMinimumSize(new java.awt.Dimension(115, 27));
        bt_next.setPreferredSize(new java.awt.Dimension(115, 27));
        bt_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        getContentPane().add(bt_next, gridBagConstraints);

        bt_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tomocomd/camps/mdlais/gui/data/tipsclose.png"))); // NOI18N
        bt_close.setText("Close");
        bt_close.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        bt_close.setMaximumSize(new java.awt.Dimension(115, 27));
        bt_close.setMinimumSize(new java.awt.Dimension(115, 27));
        bt_close.setPreferredSize(new java.awt.Dimension(115, 27));
        bt_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 12);
        getContentPane().add(bt_close, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(486, 340));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(486, 340));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(486, 340));

        text_panel.setEditable(false);
        text_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        text_panel.setMaximumSize(new java.awt.Dimension(486, 300));
        text_panel.setMinimumSize(new java.awt.Dimension(486, 300));
        text_panel.setPreferredSize(new java.awt.Dimension(486, 300));
        jScrollPane1.setViewportView(text_panel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 12);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Tips Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
        
        setVisible(false);
        
    }//GEN-LAST:event_bt_closeActionPerformed
    
    private void bt_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nextActionPerformed
        
        index = (index + 1) % tips_list.size();
        try 
        {
            jLabel1.setText("Tip: " + (index + 1) + " of " + tips_list.size());
            text_panel.setPage(getClass().getResource(tips_list.get(index)));
        }
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_bt_nextActionPerformed
    
    private void bt_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prevActionPerformed
        
        if(index != 0)
        {
            index = (index - 1);
        }
        else
        {
            index = tips_list.size() - 1;
        }
        
        try 
        {
            jLabel1.setText("Tip: " + (index + 1) + " of " + tips_list.size());
            text_panel.setPage(getClass().getResource(tips_list.get(index)));
        }
        catch (IOException ex) 
        {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_bt_prevActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_close;
    private javax.swing.JButton bt_next;
    private javax.swing.JButton bt_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane text_panel;
    // End of variables declaration//GEN-END:variables
}
