/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tomocomd.camps.mdlais.tools.invariants;

/**
 *
 * @author Cesar
 */
public enum InvariantType
{
    MINKOWSKI_P1, MINKOWSKI_P2, MINKOWSKI_P3, PENROSE,
    
    GEOMETRIC_MEAN, ARITHMETIC_MEAN, HARMONIC_MEAN, POTENTIAL_MEAN_P2, POTENTIAL_MEAN_P3,
    
    VARIANCE, SKEWNESS, KURTOSIS, STANDARD_DEVIATION, VARIATION_COEFFICIENT, RANGE, PERCENTIL_25, PERCENTIL_50, PERCENTIL_75, I50, MAX, MIN,
    
    GOWAWA, CHOQUET,
    
    AUTOCORRELATION, GRAVITATIONAL, TOTAL_SUM, MEAN_INFORMATION, STANDARIZED_INFORMATION, TOTAL_INFORMATION, IVANCIUC_BALABAN, ELECTROTOPOLOGICAL_STATE, KIER_HALL,RADIAL_DISTRIBUTION_FUNCTION, GEARY,
    
    POTENTIAL_CHARGE_DISTRIBUTION, CONNECTIVE_ECCENTRICITY_INDEX,INTERACTION_SPECTRUM, MORSE, AMPHIPHILIC_MOMENTS, ENTROPY, BFT
}
